services:
  - type: web
    name: joka-hotel
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: JWT_SECRET
        generateValue: true
      - key: NODE_ENV
        value: production
    disk:
      name: joka-data
      mountPath: /opt/render/project/src
      sizeGB: 1
